### ISSUE TITLE
Error from Python 3

### ISSUE THREAD

**Issue by azfayel** [diogo-fern/malsub#2]
Hello,
i install malsub and met the requirements but i have an error  
python3 malsub.py -vva vt -su yahoo.fr
Traceback (most recent call last):
  File "malsub.py", line 56, in <module>
    from malsub.core import main
  File "/var/tmp/malsub-master/malsub/core/main.py", line 25
    out.error(f"input service(s) \"{','.join(inv)}\" unknown")
                                                            ^
SyntaxError: invalid syntax
Could you help me ?

Regards,

Richard

**Comment by diogo-fernan** [comment]
Hi Richard,

What Python version are you running?
malsub is a Python 3.6.x framework, reason for which it seems to be the cause of the error due to the usage of f-strings (new in Python 3.6).

Diogo

**Comment by azfayel** [comment]
Hello Diego Il use the version 3.6.I will updated and check. Thank you for your promptness. Richard Le 28 mars 2017 2:21 PM, Diogo Fernandes <notifications@github.com> a écrit :Hi Richard,
What Python version are you running?
malsub is a Python 3.6.x framework, reason for which it seems to be the cause of the error due to the usage of f-strings (new in Python 3.6).
Diogo

**Comment by diogo-fernan** [comment]
I cannot reproduce your error. The output should be the following when selecting unknown services:

```
$ python3 malsub.py -a unrecognized_service
[!]   error Wed 29 Mar 2017 06:55:50.130189 +0000 UTC: input service(s) "unrecognized_service" unknown
```

However, it seems like line 25 in your `main.py` is missing escaped double quotes, as follows (https://github.com/diogo-fernan/malsub/blob/master/malsub/core/main.py#L25):

`out.error(f"input service(s) \"{','.join(inv)}\" unknown")`

Can you check that line?

Also make sure that Python outputs the following version:

```
 $ python3 -V
Python 3.6.0
```

**Comment by azfayel** [comment]
Hello Diego I add python 3.6 to kali and it works fine now. Thank your for your attention. Regards Richard Le 29 mars 2017 9:05 AM, Diogo Fernandes <notifications@github.com> a écrit :I cannot reproduce your error. The output should be the following when selecting unknown services:
$ python3 malsub.py -a unrecognized_service
[!]   error Wed 29 Mar 2017 06:55:50.130189 +0000 UTC: input service(s) "unrecognized_service" unknown

However, it seems like line 25 in your main.py is missing escaped double quotes, as follows (https://github.com/diogo-fernan/malsub/blob/master/malsub/core/main.py#L25):
out.error(f"input service(s) \"{','.join(inv)}\" unknown")
Can you check that line?
Also make sure that Python outputs the following version:
 $ python3 -V
Python 3.6.0

**Comment by diogo-fernan** [comment]
Good that you sorted it out!
